version: "3.3"

services:
  kong:
    build:
      context: .
    volumes:
      - ./kong-declarative-config.yaml:/tmp/kong-declarative-config.yaml
      - ./kong/plugins/response-cache:/usr/local/share/lua/5.1/kong/plugins/response-cache
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong-declarative-config.yaml
      KONG_PLUGINS: bundled,response-cache
      KONG_LOG_LEVEL: debug
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"

  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning #--requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # volumes:
    #   - cache:/data
