_format_version: "1.1"

services:
  - name: plugin-test-srv
    url: https://mockbin.com/request
    routes:
      - name: request-route
        methods:
          - GET
        paths:
          - "/request/(?<aggregateID>allan)"
    plugins:
      - name: response-cache
        config:
          cache_ttl: 0
          strategy: redis
          content_type:
            - application/json
          redis:
            database: 0
            host: cache
            port: 6379
          # key_mapper:
          #   - source: "path"
          #     param: "aggregateID"
