name: "Test"

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request: {}
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # every day at midnight, to test against nightlies

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        kongVersion:
          - "3.1.x"

    steps:
      - uses: actions/checkout@v3

      - uses: Kong/kong-pongo-action@v1
        with:
          pongo_version: master
          kong_version: ${{ matrix.kongVersion }}

      - run: |
          pongo run -- --coverage
          cat luacov.report.out
